#ifndef SPHE_AUDIO_CONTRACT_H
#define SPHE_AUDIO_CONTRACT_H

/*
 * Canonical recovered audio vocabulary for the preserved Audio Rush
 * SPHE8202R firmware.
 *
 * Rules:
 * - names below represent recovered behavior contracts, not guessed silicon
 *   capabilities;
 * - UNKNOWN semantics remain neutral instead of being given attractive names;
 * - the saved Analysis project is the canonical semantic authority; this
 *   header mirrors confirmed vocabulary for replacement-source reuse.
 */

enum sphe_audio_action {
    SPHE_AUDIO_ACTION_PIPELINE_MODE       = 0x00,
    SPHE_AUDIO_ACTION_OUTPUT_MODE         = 0x01,
    SPHE_AUDIO_ACTION_MASTER_VOLUME       = 0x02,
    SPHE_AUDIO_ACTION_KEY                 = 0x03,
    SPHE_AUDIO_ACTION_ECHO                = 0x04,
    SPHE_AUDIO_ACTION_SURROUND            = 0x05,
    SPHE_AUDIO_ACTION_SUBWOOFER           = 0x06,
    SPHE_AUDIO_ACTION_SPDIF_HW            = 0x07,
    SPHE_AUDIO_ACTION_EQ_PROCESSING       = 0x08,
    SPHE_AUDIO_ACTION_DECODER_STATE       = 0x09,
    SPHE_AUDIO_ACTION_MIC1                = 0x0A,
    SPHE_AUDIO_ACTION_SPEAKER_DELAY       = 0x0B,
    SPHE_AUDIO_ACTION_INVALID_0C          = 0x0C,
    SPHE_AUDIO_ACTION_INVALID_0D          = 0x0D,
    SPHE_AUDIO_ACTION_GM5                 = 0x0E,
    SPHE_AUDIO_ACTION_GAIN_FAMILY_1A      = 0x0F,
    SPHE_AUDIO_ACTION_GAIN_FAMILY_1B      = 0x10,
    SPHE_AUDIO_ACTION_GAIN_FAMILY_1C      = 0x11,
    SPHE_AUDIO_ACTION_GAIN_FAMILY_1D      = 0x12,
    SPHE_AUDIO_ACTION_GAIN_FAMILY_15      = 0x13,
    SPHE_AUDIO_ACTION_GAIN_FAMILY_1E      = 0x14,
    SPHE_AUDIO_ACTION_CONSTANT_0B01       = 0x15,
    SPHE_AUDIO_ACTION_MIC2_TRIGGER        = 0x16,
    SPHE_AUDIO_ACTION_SPEAKER_TOPOLOGY    = 0x17,
    SPHE_AUDIO_ACTION_CONSTANT_2700       = 0x18,
    SPHE_AUDIO_ACTION_FAMILY_2800         = 0x19,
    SPHE_AUDIO_ACTION_CONSTANT_2900       = 0x1A,
};

enum sphe_audio_command_family {
    SPHE_AUDIO_CMD_PIPELINE        = 0x0200,
    SPHE_AUDIO_CMD_OUTPUT_MODE     = 0x0300,
    SPHE_AUDIO_CMD_KEY             = 0x0500,
    SPHE_AUDIO_CMD_ECHO            = 0x0600,
    SPHE_AUDIO_CMD_SURROUND        = 0x0700,
    SPHE_AUDIO_CMD_SUBWOOFER       = 0x0800,
    SPHE_AUDIO_CMD_SPDIF_HW        = 0x0900,
    SPHE_AUDIO_CMD_EQ_PROCESSING   = 0x0A00,
    SPHE_AUDIO_CMD_MASTER_VOLUME    = 0x1100,
    SPHE_AUDIO_CMD_MIC1             = 0x1200,
    SPHE_AUDIO_CMD_CONSTANT_0B01   = 0x0B00,
    SPHE_AUDIO_CMD_SPEAKER_DELAY   = 0x0C00,
    SPHE_AUDIO_CMD_DECODER_STATE   = 0x0D00,
    SPHE_AUDIO_CMD_GM5             = 0x0E00,
    SPHE_AUDIO_CMD_GAIN_15         = 0x1500,
    SPHE_AUDIO_CMD_MIC2        = 0x1700,
    SPHE_AUDIO_CMD_GAIN_1A         = 0x1A00,
    SPHE_AUDIO_CMD_GAIN_1B         = 0x1B00,
    SPHE_AUDIO_CMD_GAIN_1C         = 0x1C00,
    SPHE_AUDIO_CMD_GAIN_1D         = 0x1D00,
    SPHE_AUDIO_CMD_GAIN_1E         = 0x1E00,
    SPHE_AUDIO_CMD_SPEAKER_TOPOLOGY = 0x2300,
    SPHE_AUDIO_CMD_CONSTANT_2700   = 0x2700,
    SPHE_AUDIO_CMD_FAMILY_2800     = 0x2800,
    SPHE_AUDIO_CMD_CONSTANT_2900   = 0x2900,
};

enum sphe_audio_pipeline_command {
    SPHE_AUDIO_PIPELINE_START = 0x0201,
    SPHE_AUDIO_PIPELINE_STOP  = 0x0203,
    SPHE_AUDIO_PIPELINE_PAUSE = 0x0204,
};

enum sphe_wave_format_tag {
    SPHE_WAVE_FORMAT_PCM          = 0x0001,
    SPHE_WAVE_FORMAT_MS_ADPCM     = 0x0002,
    SPHE_WAVE_FORMAT_ALAW         = 0x0006,
    SPHE_WAVE_FORMAT_MULAW        = 0x0007,
    SPHE_WAVE_FORMAT_IMA_ADPCM    = 0x0011,
    SPHE_WAVE_FORMAT_MPEG1_AUDIO  = 0x0050,
    SPHE_WAVE_FORMAT_MP3          = 0x0055,
    SPHE_WAVE_FORMAT_WMA_STANDARD = 0x0161,
};

enum sphe_wave_route_state {
    SPHE_WAVE_ROUTE_STATE_PCM_FAMILY     = 0x00000010,
    SPHE_WAVE_ROUTE_STATE_MPEG_AUDIO     = 0x00000100,
    SPHE_WAVE_ROUTE_STATE_WMA            = 0x00004000,
    SPHE_WAVE_ROUTE_STATE_LEGACY_WAVE    = 0x04000000,
};

enum sphe_wave_service_mode {
    SPHE_WAVE_SERVICE_MODE_PCM       = 0x40,
    SPHE_WAVE_SERVICE_MODE_IMA_ADPCM = 0x80,
};

enum sphe_sample_rate_boundary_hz {
    SPHE_RATE_8K_MIN_HZ      = 7500,
    SPHE_RATE_8K_MAX_HZ      = 8500,
    SPHE_RATE_11025_MIN_HZ   = 10525,
    SPHE_RATE_11025_MAX_HZ   = 11525,
    SPHE_RATE_16K_MIN_HZ     = 15500,
    SPHE_RATE_16K_MAX_HZ     = 16500,
    SPHE_RATE_22050_MIN_HZ   = 21550,
    SPHE_RATE_22050_MAX_HZ   = 22550,
    SPHE_RATE_32K_MIN_HZ     = 31500,
    SPHE_RATE_32K_MAX_HZ     = 32500,
};

enum sphe_decoder_state {
    SPHE_DECODER_STATE_WMA = 0x00004000,
    SPHE_DECODER_STATE_PCM = 0x00008000,
    SPHE_DECODER_STATE_AC3 = 0x00010000,
    SPHE_DECODER_STATE_DTS = 0x00020000,
    SPHE_DECODER_STATE_AUX = 0x00040000,
};

enum sphe_decoder_audio_status_layout {
    SPHE_DECODER_STATUS_TYPE_MASK         = 0x0007,
    SPHE_DECODER_STATUS_AUX_FIELD_MASK    = 0x0038,
    SPHE_DECODER_STATUS_AUX_FIELD_SHIFT   = 3,
    SPHE_DECODER_STATUS_TABLE_INDEX_MASK  = 0xFF00,
    SPHE_DECODER_STATUS_TABLE_INDEX_SHIFT = 8,
};

enum sphe_decoder_hardware_type {
    SPHE_DECODER_HW_PCM           = 0,
    SPHE_DECODER_HW_AC3           = 1,
    SPHE_DECODER_HW_DTS_A         = 2,
    SPHE_DECODER_HW_DTS_B         = 3,
    SPHE_DECODER_HW_NO_SIGNAL_MIN = 4,
};

enum sphe_spdif_output_option {
    SPHE_SPDIF_OFF = 0x12,
    SPHE_SPDIF_RAW = 0x75,
    SPHE_SPDIF_PCM = 0x77,
};

enum sphe_spdif_hardware_mode {
    SPHE_SPDIF_HW_OFF = 0,
    SPHE_SPDIF_HW_PCM = 1,
    SPHE_SPDIF_HW_RAW = 2,
};

enum sphe_audio_format_mode {
    SPHE_AUDIO_FORMAT_MODE_1    = 0x0001,
    SPHE_AUDIO_FORMAT_MODE_2    = 0x0002,
    SPHE_AUDIO_FORMAT_MODE_4    = 0x0004,
    SPHE_AUDIO_FORMAT_MODE_1000 = 0x1000,
    SPHE_AUDIO_FORMAT_MODE_2000 = 0x2000,
    SPHE_AUDIO_FORMAT_MODE_4000 = 0x4000,
};

enum sphe_audio_service_format_field {
    SPHE_AUDIO_SERVICE_FORMAT_FOR_MODE_1    = 0x0600,
    SPHE_AUDIO_SERVICE_FORMAT_FOR_MODE_2    = 0x0700,
    SPHE_AUDIO_SERVICE_FORMAT_FOR_MODE_4    = 0x0800,
    SPHE_AUDIO_SERVICE_FORMAT_FOR_MODE_1000 = 0x0300,
    SPHE_AUDIO_SERVICE_FORMAT_FOR_MODE_2000 = 0x0400,
    SPHE_AUDIO_SERVICE_FORMAT_FOR_MODE_4000 = 0x0500,
};

enum sphe_cdrom_subtype_boundary {
    SPHE_CDROM_SUBTYPE_MODE2_SINGLE = 0,
    SPHE_CDROM_SUBTYPE_MODE1_MIN    = 1,
    SPHE_CDROM_SUBTYPE_MODE1_MAX    = 5,
    SPHE_CDROM_SUBTYPE_MODE2_MIN    = 6,
    SPHE_CDROM_SUBTYPE_MODE2_MAX    = 10,
    SPHE_CDROM_SUBTYPE_MODE4_MIN    = 11,
};

enum sphe_downsample_mode {
    SPHE_DOWNSAMPLE_48K  = 0,
    SPHE_DOWNSAMPLE_96K  = 1,
    SPHE_DOWNSAMPLE_192K = 2,
};

enum sphe_downmix_option {
    SPHE_DOWNMIX_STEREO = 0x31,
    SPHE_DOWNMIX_OFF    = 0x7B,
    SPHE_DOWNMIX_LT_RT  = 0xF7,
    SPHE_DOWNMIX_VSS    = 0xF8,
};

enum sphe_gm5_option {
    SPHE_GM5_OFF   = 0x7B,
    SPHE_GM5_MODE1 = 0x9F,
    SPHE_GM5_MODE2 = 0xA0,
};

enum sphe_surround_mode {
    SPHE_SURROUND_OFF     = 0,
    SPHE_SURROUND_CONCERT = 1,
    SPHE_SURROUND_CHURCH  = 2,
    SPHE_SURROUND_PASSIVE = 3,
    SPHE_SURROUND_WIDE    = 4,
    SPHE_SURROUND_LIVE    = 5,
};

enum sphe_audio_preset_menu_page {
    SPHE_AUDIO_PRESET_PAGE_SURROUND = 0,
    SPHE_AUDIO_PRESET_PAGE_EQ       = 1,
    SPHE_AUDIO_PRESET_PAGE_BAND     = 2,
    SPHE_AUDIO_PRESET_PAGE_KEY      = 3,
};

enum sphe_audio_preset_menu_substate {
    SPHE_AUDIO_PRESET_SUBSTATE_TOP_LEVEL    = 0,
    SPHE_AUDIO_PRESET_SUBSTATE_USER_EQ_EDIT = 2,
};

enum sphe_eq_option_id {
    SPHE_EQ_OPTION_STANDARD = 195,
    SPHE_EQ_OPTION_CLASSIC  = 196,
    SPHE_EQ_OPTION_ROCK     = 197,
    SPHE_EQ_OPTION_JAZZ     = 198,
    SPHE_EQ_OPTION_POP      = 199,
    SPHE_EQ_OPTION_USER     = 200,
};

enum sphe_eq_selection {
    SPHE_EQ_STANDARD = 2,
    SPHE_EQ_CLASSIC  = 3,
    SPHE_EQ_ROCK     = 4,
    SPHE_EQ_JAZZ     = 5,
    SPHE_EQ_POP      = 6,
    SPHE_EQ_USER     = 7,
};

enum sphe_speaker_channel {
    SPHE_SPEAKER_FRONT     = 0,
    SPHE_SPEAKER_CENTER    = 1,
    SPHE_SPEAKER_REAR      = 2,
    SPHE_SPEAKER_SUBWOOFER = 3,
};

enum sphe_speaker_state {
    SPHE_SPEAKER_LARGE = 0,
    SPHE_SPEAKER_SMALL = 1,
    SPHE_SPEAKER_OFF   = 2,
};

enum sphe_subwoofer_state {
    SPHE_SUBWOOFER_STATE_OFF = 0,
    SPHE_SUBWOOFER_STATE_ON  = 1,
};

enum sphe_external_mode_code {
    SPHE_EXTERNAL_MODE_0   = 0,
    SPHE_EXTERNAL_MODE_1   = 1,
    SPHE_EXTERNAL_MODE_2   = 2,
    SPHE_EXTERNAL_MODE_AUX = 3,
};

enum sphe_external_input_selector {
    SPHE_EXTERNAL_INPUT_TUNER = 0,
    SPHE_EXTERNAL_INPUT_AUX   = 1,
    SPHE_EXTERNAL_INPUT_SPDIF = 2,
};

enum sphe_source_media_state {
    SPHE_SOURCE_MEDIA_STATE_TUNER_ROUTE = 0x02,
    SPHE_SOURCE_MEDIA_STATE_AUX         = 0x0B,
    SPHE_SOURCE_MEDIA_STATE_SPDIF_IN    = 0x0D,
};

enum sphe_eq_parameter_contract {
    SPHE_EQ_PARAMETER_BASE_INDEX  = 7,
    SPHE_EQ_PARAMETER_COUNT_LIMIT = 8,
    SPHE_EQ_PARAMETER_APPLY_VALUE = 0x10,
};

enum sphe_audio_control_limit {
    SPHE_MASTER_VOLUME_MAX = 15,
    SPHE_EFFECT_INDEX_MAX = 8,
    SPHE_EQ_BAND_COUNT = 7,
    SPHE_CONTROL_SELECTION_BIAS = 2,
    SPHE_CONTROL_VALUE_UNKNOWN = 0xFF,
};

enum sphe_key_selection_contract {
    SPHE_KEY_SELECTION_BIAS = 8,
};

enum sphe_echo_profile_mode {
    SPHE_ECHO_PROFILE_MODE_OFF = 0,
    SPHE_ECHO_PROFILE_MODE_1   = 7,
    SPHE_ECHO_PROFILE_MODE_2   = 15,
    SPHE_ECHO_PROFILE_MODE_3   = 23,
    SPHE_ECHO_PROFILE_MODE_4   = 31,
    SPHE_ECHO_PROFILE_MODE_5   = 39,
    SPHE_ECHO_PROFILE_MODE_6   = 47,
    SPHE_ECHO_PROFILE_MODE_7   = 55,
};

enum sphe_echo_profile_contract {
    SPHE_ECHO_PROFILE_AUX_VALUE = 10000,
    SPHE_ECHO_PROFILE_STEP      = 8,
    SPHE_ECHO_PROFILE_FIRST_MODE = 7,
};

enum sphe_eq_gain_code {
    SPHE_EQ_GAIN_CODE_MINUS_10_DB = 3,
    SPHE_EQ_GAIN_CODE_MINUS_6_DB  = 7,
    SPHE_EQ_GAIN_CODE_MINUS_4_DB  = 9,
    SPHE_EQ_GAIN_CODE_MINUS_3_DB  = 10,
    SPHE_EQ_GAIN_CODE_MINUS_2_DB  = 11,
    SPHE_EQ_GAIN_CODE_0_DB        = 13,
    SPHE_EQ_GAIN_CODE_PLUS_2_DB   = 15,
    SPHE_EQ_GAIN_CODE_PLUS_3_DB   = 16,
    SPHE_EQ_GAIN_CODE_PLUS_5_DB   = 18,
    SPHE_EQ_GAIN_CODE_PLUS_6_DB   = 19,
    SPHE_EQ_GAIN_CODE_PLUS_8_DB   = 21,
    SPHE_EQ_GAIN_CODE_PLUS_10_DB  = 23,
};

enum sphe_user_eq_gain_contract {
    SPHE_USER_EQ_ZERO_DB_GAIN_CODE = SPHE_EQ_GAIN_CODE_0_DB,
};

enum sphe_speaker_delay_kind {
    SPHE_SPEAKER_DELAY_KIND_CENTER = 1,
    SPHE_SPEAKER_DELAY_KIND_REAR   = 2,
};

enum sphe_speaker_delay_contract {
    SPHE_CENTER_DELAY_SELECTION_BIAS = 2,
    SPHE_REAR_DELAY_SELECTION_SCALE  = 3,
    SPHE_REAR_DELAY_SELECTION_BIAS   = 6,
};

enum sphe_setup_control_id {
    SPHE_CONTROL_ECHO                 = 0x57,
    SPHE_CONTROL_DOWNSAMPLE           = 0x5B,
    SPHE_CONTROL_KEY                  = 0x5C,
    SPHE_CONTROL_DYNAMIC_RANGE        = 0x6A,
    SPHE_CONTROL_AUDIO_COMMAND_FAMILY = 0x6E,
    SPHE_CONTROL_SPDIF_OUTPUT         = 0x71,
    SPHE_CONTROL_SUBWOOFER            = 0x8B,
    SPHE_CONTROL_GM5                  = 0x9E,
    SPHE_CONTROL_MIC1                 = 0xB2,
    SPHE_CONTROL_MIC2                 = 0xB3,
    SPHE_CONTROL_CENTER_DELAY         = 0xD1,
    SPHE_CONTROL_REAR_DELAY           = 0xD2,
    SPHE_CONTROL_CENTER_SPEAKER       = 0xCD,
    SPHE_CONTROL_REAR_SPEAKER         = 0xCE,
    SPHE_CONTROL_FRONT_SPEAKER        = 0xD3,
    SPHE_CONTROL_DOWNMIX              = 0xF5,
};

enum sphe_audio_command_family_selector_option {
    SPHE_AUDIO_COMMAND_FAMILY_OPTION_0C = 0x81,
    SPHE_AUDIO_COMMAND_FAMILY_OPTION_0E = 0x82,
    SPHE_AUDIO_COMMAND_FAMILY_OPTION_0D = 0x83,
};

enum sphe_downsample_option_id {
    SPHE_DOWNSAMPLE_OPTION_48K  = 0x4F,
    SPHE_DOWNSAMPLE_OPTION_96K  = 0x50,
    SPHE_DOWNSAMPLE_OPTION_192K = 0x51,
};

enum sphe_speaker_option_id {
    SPHE_SPEAKER_OPTION_LARGE = 0x24,
    SPHE_SPEAKER_OPTION_SMALL = 0x2A,
    SPHE_SPEAKER_OPTION_OFF   = 0x7B,
    SPHE_SUBWOOFER_OPTION_ON  = 0x8D,
};

enum sphe_downsample_state_mask {
    SPHE_DOWNSAMPLE_MASK_48K  = 0x0007,
    SPHE_DOWNSAMPLE_MASK_96K  = 0x0067,
    SPHE_DOWNSAMPLE_MASK_192K = 0x0667,
};

enum sphe_control_menu_state {
    SPHE_CONTROL_MENU_STATE_BROWSE = 2,
    SPHE_CONTROL_MENU_STATE_EDIT   = 3,
};

enum sphe_control_descriptor_layout {
    SPHE_CONTROL_RESOLVE_INVALID       = 0xFFFF,
    SPHE_CONTROL_RESOLVE_GROUP_SHIFT   = 8,
    SPHE_CONTROL_RESOLVE_FIELD_MASK    = 0xFF,
    SPHE_CONTROL_DISPATCH_SIDE_EFFECTS = 1,
    SPHE_CONTROL_GROUP_COUNT           = 7,
    SPHE_CONTROL_SLOT_FIRST           = 1,
    SPHE_CONTROL_SLOT_LIMIT           = 9,
    SPHE_CONTROL_GROUP_STRIDE         = 0x75,
    SPHE_CONTROL_DESCRIPTOR_SIZE      = 0x0D,
    SPHE_CONTROL_OPTION_FIRST_OFFSET  = 0x02,
    SPHE_CONTROL_OPTION_LIMIT_OFFSET  = 0x0A,
    SPHE_CONTROL_STATE_SLOT_OFFSET    = 0x0B,
    SPHE_CONTROL_STATE_SLOT_LIMIT     = 0x41,
    SPHE_CONTROL_SELECTION_GROUP_SIZE = 9,
};

enum sphe_command_mailbox_key {
    SPHE_MAILBOX_KEY_INDEXED_BASE     = 0x4000,
    SPHE_MAILBOX_KEY_COMPLETION       = 0x454B,
    SPHE_MAILBOX_KEY_SPDIF_RAW_INIT   = 0x4627,
    SPHE_MAILBOX_KEY_SPDIF_PCM_INIT   = 0x4628,
};

enum sphe_persistent_namespace {
    /* Byte-addressed persistent namespace used by recovered control/source state. */
    SPHE_PERSIST_NAMESPACE_MAIN = 0x00A0,
};

enum sphe_persistent_offset {
    SPHE_PERSIST_OFFSET_FIRMWARE_SIGNATURE      = 0x0001,
    SPHE_PERSIST_OFFSET_CONTROL_SELECTIONS      = 0x0004,
    SPHE_PERSIST_OFFSET_CONTROL_CHECKSUM        = 0x0045,
    SPHE_PERSIST_OFFSET_AUXILIARY_CONTROL_STATE = 0x0047,
    SPHE_PERSIST_OFFSET_UNMAPPED_BLOCK_0102     = 0x0102,
    SPHE_PERSIST_OFFSET_EXTERNAL_INPUT_MODE     = 0x0136,
};

enum sphe_persistent_size {
    SPHE_PERSIST_FIRMWARE_SIGNATURE_SIZE        = 3,
    SPHE_PERSIST_CONTROL_SELECTIONS_SIZE        = SPHE_CONTROL_STATE_SLOT_LIMIT,
    SPHE_PERSIST_CONTROL_CHECKSUM_SIZE          = 2,
    SPHE_PERSIST_AUXILIARY_CONTROL_STATE_SIZE   = 0x001C,
    SPHE_PERSIST_UNMAPPED_BLOCK_0102_SIZE       = 0x0034,
    SPHE_PERSIST_EXTERNAL_INPUT_MODE_SIZE       = 1,
};

enum sphe_decoder_input_ring_capacity_bytes {
    SPHE_DECODER_INPUT_CAPACITY_SMALL    = 0x2400,
    SPHE_DECODER_INPUT_CAPACITY_NORMAL   = 0x3000,
    SPHE_DECODER_INPUT_CAPACITY_LARGE    = 0x3C00,
    SPHE_DECODER_INPUT_CAPACITY_EXTENDED = 0x6C00,
};

enum sphe_decoder_input_ring_conversion {
    SPHE_DECODER_INPUT_CAPACITY_PARAMETER_DIVISOR = 3,
};

enum sphe_decoder_profile_capacity_contract {
    SPHE_DECODER_PROFILE_CAPACITY_EXTRA_UNITS = 3,
};

enum sphe_audio_service_state {
    SPHE_AUDIO_SERVICE_STOPPED = 0,
    SPHE_AUDIO_SERVICE_RUNNING = 1,
    SPHE_AUDIO_SERVICE_PAUSED  = 2,
};

enum sphe_audio_service_register_offset {
    SPHE_AUDIO_SERVICE_REG_RUN_CONTROL         = 0x0130,
    SPHE_AUDIO_SERVICE_REG_COMMAND             = 0x04C0,
    SPHE_AUDIO_SERVICE_REG_ARGUMENT            = 0x04C4,
    SPHE_AUDIO_SERVICE_REG_INPUT_PRODUCER_WORD = 0x04C8,
    SPHE_AUDIO_SERVICE_REG_INPUT_CONSUMER_WORD = 0x04CC,
    SPHE_AUDIO_SERVICE_REG_INPUT_CAPACITY      = 0x04D0,
    SPHE_AUDIO_SERVICE_REG_STATE               = 0x04D4,
    SPHE_AUDIO_SERVICE_REG_UNKNOWN_4D8         = 0x04D8,
};

enum sphe_audio_service_run_control {
    SPHE_AUDIO_SERVICE_COMMIT     = 1,
    SPHE_AUDIO_SERVICE_TRANSITION = 3,
};

enum sphe_audio_service_wait_contract {
    SPHE_AUDIO_SERVICE_DISPATCH_POLL_BUDGET = 100000,
};

enum sphe_audio_service_status_bit {
    SPHE_AUDIO_SERVICE_COMMAND_ACK = 0x8000,
};

enum sphe_decoder_service_slot {
    SPHE_SERVICE_SLOT_INPUT_RING_WORDS       = 0x01,
    SPHE_SERVICE_SLOT_SUBWOOFER              = 0x0D,
    SPHE_SERVICE_SLOT_PLAYBACK_ID_0          = 0x13,
    SPHE_SERVICE_SLOT_PLAYBACK_ID_1          = 0x14,
    SPHE_SERVICE_SLOT_PLAYBACK_ID_2          = 0x15,
    SPHE_SERVICE_SLOT_PLAYBACK_ID_3          = 0x16,
    SPHE_SERVICE_SLOT_PLAYBACK_ID_4          = 0x17,
    SPHE_SERVICE_SLOT_PLAYBACK_ID_5          = 0x18,
    SPHE_SERVICE_SLOT_PLAYBACK_ID_6          = 0x19,
    SPHE_SERVICE_SLOT_PLAYBACK_ID_7          = 0x1A,
    SPHE_SERVICE_SLOT_SPEAKER_TOPOLOGY       = 0x1B,
    SPHE_SERVICE_SLOT_DOWNMIX                = 0x21,
    SPHE_SERVICE_SLOT_GM5                    = 0x23,
    SPHE_SERVICE_SLOT_AUX_CAPTURE_PAIR       = 0x32,
};

enum sphe_aux_capture_pair_selector {
    SPHE_AUX_CAPTURE_PAIR_0E_0F = 4,
    SPHE_AUX_CAPTURE_PAIR_10_11 = 5,
};

enum sphe_decoder_profile_selector_contract {
    SPHE_DECODER_PROFILE_SELECTOR_BASE  = 0xF8,
    SPHE_DECODER_PROFILE_FALLBACK_INDEX = 8,
};

struct sphe_decoder_profile_descriptor {
    unsigned int packed_source;
    unsigned short field_a;
    unsigned short field_b;
    unsigned short field_c;
};

enum sphe_resident_channel_id {
    SPHE_RESIDENT_CAPTURE_ALT_A    = 0x0E,
    SPHE_RESIDENT_CAPTURE_ALT_B    = 0x0F,
    SPHE_RESIDENT_CAPTURE_TARGET_A = 0x10,
    SPHE_RESIDENT_CAPTURE_TARGET_B = 0x11,
};

enum sphe_resident_mailbox_command {
    SPHE_RESIDENT_SET_AUDIO_OUTPUT_BLOCK = 0x62,
    SPHE_RESIDENT_GET_AUDIO_INPUT_BLOCK  = 0x63,
};

enum sphe_resident_route_source_slot {
    SPHE_RESIDENT_SOURCE_TARGET_A = 0,
    SPHE_RESIDENT_SOURCE_TARGET_B = 1,
    SPHE_RESIDENT_SOURCE_ALT_A    = 2,
    SPHE_RESIDENT_SOURCE_ALT_B    = 3,
};

enum sphe_resident_route_status_bit {
    SPHE_RESIDENT_COEFFICIENT_BUSY = 0x1000,
    SPHE_RESIDENT_ROUTE_BUSY       = 0x2000,
};

struct sphe_resident_audio_descriptor {
    unsigned short channel_id;
    unsigned short ring_base;
    unsigned short ring_size;
    unsigned short runtime_state;
    unsigned short runtime_counter;
};

/* Canonical control-descriptor/table addresses. */
#define SPHE_CONTROL_DESCRIPTOR_BASE              0x80707EACU
#define SPHE_CONTROL_DISPATCH_JUMP_TABLE          0x807081E0U
#define SPHE_CONTROL_SELECTION_BASE               0x800066B0U
#define SPHE_CONTROL_STATE_BASE                   0x80006810U
#define SPHE_ADDR_RESOLVE_CONTROL_ID_TO_GROUP_SLOT 0x80777E20U
#define SPHE_ADDR_DISPATCH_CONTROL_OPTION          0x80776210U
#define SPHE_ADDR_DISPATCH_SPECIAL_CONTROL_SELECTION 0x8077761CU

/* Canonical recovered action-node addresses used by replacement-source code. */
#define SPHE_ADDR_DISPATCH_AUDIO_HARDWARE_ACTION  0x806FFD1CU
#define SPHE_ADDR_SET_MASTER_VOLUME_LEVEL       0x8070129CU
#define SPHE_ADDR_TOGGLE_MASTER_MUTE              0x806F9D18U
#define SPHE_ADDR_APPLY_SPDIF_HARDWARE_OUTPUT_MODE       0x80702BA0U
#define SPHE_ADDR_APPLY_DECODER_OUTPUT_MODE       0x80702BD0U
#define SPHE_ADDR_APPLY_SPEAKER_DELAY_PARAMETER             0x80702C60U
#define SPHE_ADDR_APPLY_ECHO_PROFILE_INDEX              0x80702C8CU
#define SPHE_ADDR_APPLY_MIC1_LEVEL                0x80702B48U
#define SPHE_ADDR_APPLY_MIC2_SELECTION            0x80702B74U
#define SPHE_ADDR_SELECT_AUDIO_FORMAT_MODE_BY_SAMPLE_RATE 0x807019BCU
#define SPHE_ADDR_APPLY_DOWNSAMPLE_RATE_MODE           0x80701B80U
#define SPHE_ADDR_APPLY_SPEAKER_CONFIGURATION        0x8070106CU
#define SPHE_ADDR_APPLY_EXTERNAL_INPUT_HARDWARE_MODE  0x806FED88U
#define SPHE_ADDR_WRITE_EXTERNAL_INPUT_MODE_CODE   0x8071DB1CU
#define SPHE_ADDR_PREPARE_EXTERNAL_INPUT_TRANSITION 0x806FABA0U
#define SPHE_ADDR_PREPARE_SPDIF_INPUT_DECODER       0x8071E1B0U
#define SPHE_ADDR_HANDLE_AUX_INPUT_TRANSITION        0x8071E4F0U
#define SPHE_ADDR_HANDLE_SPDIF_INPUT_TRANSITION      0x8071EE94U
#define SPHE_ADDR_REAPPLY_CURRENT_ECHO_SELECTION            0x8077CA14U
#define SPHE_ADDR_REAPPLY_CURRENT_MIC1_SELECTION            0x8077CA44U
#define SPHE_ADDR_WRITE_PERSISTENT_RECORD         0x806E1FC0U
#define SPHE_ADDR_READ_PERSISTENT_RECORD          0x806E2100U
#define SPHE_ADDR_CALCULATE_CONTROL_SELECTION_CHECKSUM 0x8077BFA4U
#define SPHE_ADDR_SAVE_CONTROL_SELECTION_SLOT     0x8077C07CU
#define SPHE_ADDR_SAVE_AUXILIARY_CONTROL_STATE    0x8077C110U
#define SPHE_ADDR_CHECK_SPDIF_DECODER_REAPPLY_CONDITION     0x8077C42CU
#define SPHE_ADDR_HANDLE_MIC1_LEVEL_INCREASE      0x806FA8B4U
#define SPHE_ADDR_HANDLE_MIC1_LEVEL_DECREASE      0x806FA920U
#define SPHE_ADDR_APPLY_SPDIF_OUTPUT_OPTION       0x807759E0U
#define SPHE_ADDR_APPLY_DOWNMIX_OPTION            0x80775800U
#define SPHE_ADDR_HANDLE_GM5_CONTROL_OPTION                0x80775F3CU
#define SPHE_ADDR_APPLY_DYNAMIC_RANGE_CONTROL             0x807769B8U
#define SPHE_ADDR_LOAD_SEVEN_BAND_EQ_PRESET                 0x806E8960U
#define SPHE_ADDR_APPLY_SEVEN_BAND_EQ_CURVE                  0x806E8ED0U
#define SPHE_ADDR_APPLY_CURRENT_SEVEN_BAND_EQ_PRESET         0x806E89E4U
#define SPHE_ADDR_SET_SPEAKER_CHANNEL_STATE       0x80701168U
#define SPHE_ADDR_APPLY_SUBWOOFER_STATE           0x80701268U
#define SPHE_ADDR_SET_DSP_PARAMETER_WORD24        0x88001358U
#define SPHE_ADDR_GET_DSP_PARAMETER_WORD24        0x8800138CU
#define SPHE_ADDR_WAIT_FOR_AUDIO_SERVICE_CONDITIONS   0x88001C78U
#define SPHE_ADDR_GET_DECODER_INPUT_RING_FREE_BYTES     0x88001CD0U
#define SPHE_ADDR_GET_DECODER_INPUT_RING_FREE_BYTES_VIA_RUNTIME 0x80702824U
#define SPHE_ADDR_GET_DECODER_INPUT_RING_QUEUED_BYTES_VIA_RUNTIME 0x80702844U
#define SPHE_ADDR_SET_DECODER_INPUT_RING_PRODUCER_WORD 0x80702904U
#define SPHE_ADDR_GET_DECODER_INPUT_RING_CONSUMER_WORD 0x80702910U
#define SPHE_ADDR_GET_DECODER_INPUT_RING_ALIGNED_CAPACITY      0x8070291CU
#define SPHE_ADDR_GET_AUDIO_SERVICE_INPUT_CAPACITY     0x80702928U
#define SPHE_ADDR_GET_AUDIO_SERVICE_STATE              0x80702934U
#define SPHE_ADDR_SET_AUDIO_SERVICE_REGISTER_4D8       0x80702940U

/* Confirmed resident runtime tables referenced by audio-control actions. */
#define SPHE_RUNTIME_MASTER_VOLUME_GAIN_TABLE 0x88012CA0U
#define SPHE_RUNTIME_ECHO_PROFILE_TABLE       0x88012CC0U

/* Shared MIPS gp base used by the primary firmware modules. */
#define SPHE_SHARED_GP_BASE                        0x80002B00U

/* Confirmed AP1 live-state addresses. */
#define SPHE_STATE_AUDIO_DECODER_STATE               0x80003198U
#define SPHE_STATE_EXTERNAL_INPUT_MODE_CODE          0x80002C2BU
#define SPHE_STATE_PREVIOUS_EXTERNAL_INPUT_MODE_CODE 0x80002C2CU
#define SPHE_STATE_EXTERNAL_INPUT_SELECTOR           0x800032FAU
#define SPHE_STATE_SOURCE_MEDIA_STATE                0x800032A5U
#define SPHE_STATE_MASTER_VOLUME_LEVEL               0x80003332U
#define SPHE_STATE_MASTER_MUTE_FLAG                  0x800032B5U
#define SPHE_STATE_DYNAMIC_RANGE_SELECTION           0x8000332CU
#define SPHE_STATE_DECODER_AUDIO_STATUS              0x800022E4U
#define SPHE_STATE_DOWNSAMPLE_STATE_MASK             0x80003244U
#define SPHE_STATE_AUDIO_FORMAT_MODE_STORAGE            0x80003274U
#define SPHE_STATE_SPDIF_HARDWARE_MODE               0x800042B3U
#define SPHE_STATE_SPDIF_OUTPUT_SELECTION_SLOT       0x8000681BU
#define SPHE_STATE_AUDIO_COMMAND_FAMILY_SELECTION    0x800042FEU
#define SPHE_STATE_SURROUND_SELECTION                0x80002B0CU
#define SPHE_STATE_AUDIO_PRESET_MENU_PAGE            0x80002B18U
#define SPHE_STATE_AUDIO_PRESET_MENU_SUBSTATE        0x80002B19U
#define SPHE_STATE_AUDIO_PRESET_WORKING_VALUE        0x80002B22U
#define SPHE_STATE_CONTROL_BROWSER_GROUP_INDEX       0x80002B29U
#define SPHE_STATE_CONTROL_BROWSER_SLOT_INDEX        0x80002B2AU
#define SPHE_STATE_CONTROL_BROWSER_OPTION_INDEX      0x80002B2BU
/* Current seven-band EQ preset index (STANDARD..USER). */
#define SPHE_STATE_EQ_PRESET_INDEX                   0x80002B0DU
#define SPHE_STATE_USER_EQ7_CURVE                    0x80002B10U
#define SPHE_STATE_MIC1_LEVEL_INDEX                  0x80003297U
#define SPHE_STATE_MIC2_LEVEL_INDEX                  0x80003324U
#define SPHE_STATE_KEY_CONTROL_INDEX                 0x80003289U
#define SPHE_STATE_KEY_CONTROL_SELECTION_SLOT        0x8000681FU
#define SPHE_STATE_DYNAMIC_RANGE_SELECTION_SLOT      0x8000682BU
#define SPHE_STATE_SPEAKER_CENTER_DELAY_SELECTION_SLOT 0x80006828U
#define SPHE_STATE_SPEAKER_REAR_DELAY_SELECTION_SLOT   0x80006829U
#define SPHE_STATE_ECHO_PROFILE_INDEX                0x8000333AU
#define SPHE_STATE_ECHO_CONTROL_SELECTION_SLOT       0x8000681DU
#define SPHE_STATE_MIC1_CONTROL_SELECTION_SLOT       0x8000681EU
#define SPHE_STATE_SPEAKER_FRONT_STATE               0x80003327U
#define SPHE_STATE_SPEAKER_CENTER_STATE              0x800032DCU
#define SPHE_STATE_SPEAKER_REAR_STATE                0x8000330EU
#define SPHE_STATE_SPEAKER_SUBWOOFER_STATE           0x800032D6U
#define SPHE_STATE_SPEAKER_TOPOLOGY_WORD             0x80003050U

#endif
